quarkus:
  http:
    root-path: /api
  devservices:
    enabled: false
  datasource:
    notify:
      db-kind: oracle
      username: notify
      password: notify
      jdbc:
        url: jdbc:oracle:thin:@//localhost:1521/ORCL
        max-size: 20
      health:
        enabled: true
    cim:
      db-kind: oracle
      username: cimback
      password: cimback
      jdbc:
        url: jdbc:oracle:thin:@//localhost:1521/ORCL
        max-size: 20
      health:
        enabled: true
  hibernate-orm:
    notify:
      datasource: notify
      database:
        generation: none
      log:
        sql: true
      packages: com.example.notify.entity
    cim:
      datasource: cim
      database:
        generation: none
      log:
        sql: true
      packages: com.example.cim.entity


  smallrye-openapi:
    info:
      title: My Quarkus API
      version: 1.0.0
      description: API for my Quarkus application
  swagger-ui:
    path: /swagger-ui
    always-include: true


  smallrye-metrics:
    path: /q/metrics
    jaxrs: true
  health:
    extensions:
      enabled: true


  rest-client:
    test-service:
      url: http://localhost:8081/test-service
    scope: jakarta.inject.Singleton
    connect-timeout: 10000
    read-timeout: 15000
    enable-compression: true
    logging:
      scope: request-response
      body-limit: 200

  redis:
    hosts: redis://localhost:6379
    # password: mypassword
  cache:
    redis:
      expire-after-write: 600s
      category-cache:
        expire-after-write: 300s
        prefix: category-cache
#  log:
#    level: DEBUG
#    category:
#      "io.smallrye.reactive.messaging.rabbitmq":
#        level: DEBUG

rabbitmq-host: localhost
rabbitmq-port: 5672
rabbitmq-username: admin
rabbitmq-password: admin
rabbitmq-virtual-host: /
mp:
  messaging:
    # ----- OUTGOING -----
    outgoing:
      category-out:
        connector: smallrye-rabbitmq
        exchange:
          name: category-exchange
          type: direct
          durable: true
        default-routing-key: category.created
        delivery-mode: persistent
        retries: 5
        reconnect-attempts: 10
        reconnect-interval: 5

    # ----- INCOMING -----
    incoming:
      category-in:
        connector: smallrye-rabbitmq
        queue:
          name: category-queue
          durable: true
        exchange:
          name: category-exchange
          type: direct
          durable: true
        routing-keys: category.created
        auto-acknowledgement: true
        max-incoming-inflight: 2


